### Get all contacts
GET http://localhost:3000/contacts

### Get a specific contact
GET http://localhost:3000/contacts/67337169f70203f9695f28a2



### Get all contacts from render page
GET https://project1-uxpv.onrender.com/contacts

### Get a specific contact from render page
GET https://project1-uxpv.onrender.com/contacts/67337169f70203f9695f28a2
